spring:
    main:
        banner-mode: "log"
    batch:
        job:
            enabled: false

tool:
    tableNames:
        adjustment: "CTF_Adjustments"
        adjustmentType: "Adj_Type"
        categoryProductJoin: "tblCategoryProductJoin"
        comment: "CTF_Comments"
        facility: "Facility"
        item: "CTF_Item"
        main: "CTF_Main"
        product: "Product"
        program: "Program"
    parameters:
        startDate: 2012-01-01
        endDate: 2017-12-31
        numberOfPeriodsToAverage: 2
        creator: "scm"
        requestedQuantityExplanation: "transferred from supply manager"
        timeZone: "CAT"
        orderNumberConfiguration:
            orderNumberPrefix: "O"
            includeOrderNumberPrefix: true
            includeProgramCode: false
            includeTypeSuffix: false
    configuration:
        createRequisitionTemplate: true
        accessFile: "data.mdb"
        olmis:
            dialect: "org.hibernate.spatial.dialect.postgis.PostgisDialect"
            showSql: false
            dataSource:
                connectionProperties:
                    stringtype: "unspecified"
                driverClass: "org.postgresql.Driver"
                host: "localhost"
                port: 5432
                database: "open_lmis"
                username: "postgres"
                password: "p@ssw0rd"
        batch:
            chunk: 10
            skipPolicy: "org.springframework.batch.core.step.skip.AlwaysSkipItemSkipPolicy"
            migration: true
            skipPeriods: true
            removeDuplicates: true
    mapping:
        programs:
            - code: "em"
              categories:
                  - "(A) TABLETS/CAPSULES"
                  - "(B) INJECTABLES"
                  - "(C) VACCINES & TOXOIDS"
                  - "(D) GALENICALS: SYRUPS/ELIXIRS/SUSPENSIONS, TOPICAL PREPARATIONS & DISINFECTANTS"
                  - "(E) DISPENSARY ITEMS"
                  - "(F) SURGICAL DRESSINGS"
                  - "(G) SUTURES"
                  - "(H) SURGICAL & HOSPITAL EQUIPMENT"
                  - "(I) X-RAY FILMS & SUPPLIES"
                  - "(J) DENTAL ITEMS"
                  - "CLASS D: Raw Materials"
                  - "CLASS M: Laboratory Reagents and Materials (Supplies)"
                  - "CLASS Q: Miscellaneous Items"
                  - "CLASS R: Hospital Bedings"
                  - "CLASS S: Slow Moving Items"
                  - "MENTAL SPECIAL"
                  - "SURGICAL EQUIPMENT"
              warehouses:
                  - geographicZone: "central"
                    code: "cmstc"
                  - geographicZone: "south"
                    code: "cmsts"
                  - geographicZone: "northern"
                    code: "cmstn"
            - code: "mal"
              categories:
                  - "(K) MALARIA PROGRAM MEDICINES & HEALTH SUPPLIES"
              warehouses:
                  - code: "program"
            - code: "fp"
              categories:
                  - "(L) REPRODUCTIVE HEALTH PROGRAM MEDICINES & HEALTH SUPPLIES"
              warehouses:
                  - code: "program"
            - code: "hiv"
              categories:
                  - "(M) HIV/AID CONTROL PROGRAM MEDICINES & HEALTH SUPPLIES"
              warehouses:
                  - code: "program"
            - code: "tb"
              categories:
                  - "(N) TUBERCULOSIS PROGRAM MEDICINES"
              warehouses:
                  - code: "program"
        facilities:
            "A": "A"
            "B": "B"
        products:
            "Chlorpromazine 25mg": "A0110"
        stockAdjustmentReasons:
            "DE Credit": "Transfer In"
            "DE Debit": "Transfer Out"
        categoryProductJoins:
            10: 20
            15: 30
