spring:
    main:
        banner-mode: "log"
    batch:
        job:
            enabled: false

tool:
    parameters:
        interval:
            days: 0
            months: 0
            years: 5
        creator: "supply chain manager"
        requestedQuantityExplanation: "transferred from supply manager"
        timeZone: "CAT"
        orderNumberConfiguration:
            orderNumberPrefix: "O"
            includeOrderNumberPrefix: true
            includeProgramCode: false
            includeTypeSuffix: false
    configuration:
        accessFile: "database.mdb"
        olmis:
            dialect: "org.hibernate.dialect.PostgreSQL94Dialect"
            showSql: false
            hbm2ddl: "validate"
            dataSource:
                connectionProperties:
                    stringtype: "unspecified"
                driverClass: "org.postgresql.Driver"
                host: "localhost"
                port: 5432
                database: "open_lmis"
                username: "postgres"
                password: "p@ssw0rd"
        batch:
            chunk: 10
            skipPolicy: "org.springframework.batch.core.step.skip.AlwaysSkipItemSkipPolicy"
    mapping:
        programs:
            - code: "em"
              categories:
                  - "(A) TABLETS/CAPSULES"
                  - "(B) INJECTABLES"
                  - "(C) VACCINES & TOXOIDS"
                  - "(D) GALENICALS: SYRUPS/ELIXIRS/SUSPENSIONS, TOPICAL PREPARATIONS & DISINFECTANTS"
                  - "(E) DISPENSARY ITEMS"
                  - "(F) SURGICAL DRESSINGS"
                  - "(G) SUTURES"
                  - "(H) SURGICAL & HOSPITAL EQUIPMENT"
                  - "(I) X-RAY FILMS & SUPPLIES"
                  - "(J) DENTAL ITEMS"
                  - "CLASS D: Raw Materials"
                  - "CLASS M: Laboratory Reagents and Materials (Supplies)"
                  - "CLASS Q: Miscellaneous Items"
                  - "CLASS R: Hospital Bedings"
                  - "CLASS S: Slow Moving Items"
                  - "MENTAL SPECIAL"
                  - "SURGICAL EQUIPMENT"
              warehouses:
                  - geographicZone: "central"
                    code: "cmstc"
                  - geographicZone: "south"
                    code: "cmsts"
                  - geographicZone: "northern"
                    code: "cmstn"
            - code: "mal"
              categories:
                  - "(K) MALARIA PROGRAM MEDICINES & HEALTH SUPPLIES"
              warehouses:
                  - code: "program"
            - code: "fp"
              categories:
                  - "(L) REPRODUCTIVE HEALTH PROGRAM MEDICINES & HEALTH SUPPLIES"
              warehouses:
                  - code: "program"
            - code: "hiv"
              categories:
                  - "(M) HIV/AID CONTROL PROGRAM MEDICINES & HEALTH SUPPLIES"
              warehouses:
                  - code: "program"
            - code: "tb"
              categories:
                  - "(N) TUBERCULOSIS PROGRAM MEDICINES"
              warehouses:
                  - code: "program"
        facilities:
            "A": "A"
            "B": "B"
        products:
            "Chlorpromazine 25mg": "Chlorpromazine 25mg"
        stockAdjustmentReasons:
            "DE Credit": "Transfer In"
            "DE Debit": "Transfer Out"
